name: '[QE] Cypress Runner'

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Choose another branch to test'
        required: true
        default: master
  schedule:
    # 7:30 AM UTC = 3:30 AM EDT
    - cron: '30 7 * * *'
  pull_request:
    branches:
      - master
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths-ignore:
      - docs/**
      - README.md
      - CHANGELOG.md

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  Cypress:
    runs-on: macos-10.15
    # To avoid waste Cypress tests,
    # lets run it only when the pull request is ready.
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout App
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Get Cypress Runner
        run: git clone https://github.com/vtex-apps/cy-runner.git

      - name: Cache
        uses: actions/cache@v2
        with:
          path: '~/.cache/'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Cypress
        run: |
          rm -rf .git
          yarn install --frozen-lockfile
        working-directory: ./cy-runner

      - name: Run Cypress Runner
        run: yarn cy-r
        env:
          VTEX_QE: ${{ secrets.VTEX_QE }}
          NODE_NO_WARNINGS: 1

      - name: Save results
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: cy-runner-logs
          path: cy-runner/logs
